#!/bin/bash

echo "Enter username:"
read username

uid=$(id -u "$username" 2>/dev/null)
login_count=$(who | grep -c "$username")

if [ -z "$uid" ]; then
    echo "User '$username' does not exist."
    exit 1
fi

echo "User '$username' has UID: $uid and is logged in $login_count time(s)."
